/**
 * fetch-fonts.mjs — self-host the webfonts (GDPR + performance).
 *
 * Downloads the exact weights/subsets the site uses from Google Fonts into
 * /public/fonts/ and emits /public/fonts/fonts.css with @font-face rules that
 * point at the local files. Self-hosting means visitor IPs never reach Google
 * (relevant for an EU/BE audience) and removes a third-party origin from the
 * critical path + the CSP.
 *
 * Run `npm run fonts` and commit the result when the font set changes. The
 * woff2 files + fonts.css are tracked in git so CI/Docker builds don't re-fetch.
 *
 * unicode-range is preserved per subset, so a browser still only downloads
 * latin-ext when a glyph needs it — same lazy behaviour as the Google CSS.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'public', 'fonts');

// A modern browser UA so the css2 endpoint returns woff2 (not ttf).
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

// Latin scripts only — covers EN/NL/FR. (No cyrillic/greek/vietnamese.)
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const FAMILIES = [
  { name: 'Space Grotesk', slug: 'space-grotesk', weights: [400, 500, 600, 700] },
  { name: 'JetBrains Mono', slug: 'jetbrains-mono', weights: [400, 500, 700] },
];

const FACE_RE = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const cssBlocks = [];

  for (const fam of FAMILIES) {
    const url =
      `https://fonts.googleapis.com/css2?family=${encodeURIComponent(fam.name).replace(/%20/g, '+')}` +
      `:wght@${fam.weights.join(';')}&display=swap`;
    const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

    let m;
    while ((m = FACE_RE.exec(css))) {
      const subset = m[1];
      const body = m[2];
      if (!KEEP_SUBSETS.has(subset)) continue;

      const weight = (body.match(/font-weight:\s*(\d+)/) || [])[1];
      const srcUrl = (body.match(/src:\s*url\(([^)]+)\)/) || [])[1];
      const unicode = (body.match(/unicode-range:\s*([^;]+);/) || [])[1]?.trim();
      if (!weight || !srcUrl) continue;

      const file = `${fam.slug}-${weight}-${subset}.woff2`;
      const buf = Buffer.from(await (await fetch(srcUrl, { headers: { 'User-Agent': UA } })).arrayBuffer());
      await writeFile(join(OUT_DIR, file), buf);
      console.log(`[fonts] ${file} (${(buf.length / 1024).toFixed(1)} KB)`);

      cssBlocks.push(
        `@font-face {\n` +
        `  font-family: '${fam.name}';\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url('/fonts/${file}') format('woff2');\n` +
        (unicode ? `  unicode-range: ${unicode};\n` : '') +
        `}`
      );
    }
  }

  const header =
    `/* fonts.css — self-hosted webfaces. GENERATED by scripts/fetch-fonts.mjs;\n` +
    `   do not edit by hand. Run \`npm run fonts\` to regenerate. */\n`;
  await writeFile(join(OUT_DIR, 'fonts.css'), header + cssBlocks.join('\n\n') + '\n');
  console.log(`[fonts] wrote fonts.css with ${cssBlocks.length} @font-face rule(s)`);
}

main().catch((err) => {
  console.error('[fonts] failed:', err);
  process.exit(1);
});
